name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Setup Dependencies
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_SETUP_CMD: ${{ secrets.FIREBASE_SETUP_CMD }}
        run: |
          npm install
          npx firebase login:ci
          $FIREBASE_SETUP_CMD
      - name: Run Tests
        run: npm test
